COMMON: &common
  DEBUG: False
  EXTENSION_ACTIVE: True

DEVELOPMENT: &development
  <<: *common
  EXTENSION_ACTIVE: False

TESTING: &testing
  <<: *common
  EXTENSION_STYLE: 'testing'

PRODUCTION: &production
  <<: *common
  SECRET_KEY: '27d4c2bc-0fac-4ea1-98e8-1ea1feba31f1'
  SERVER_NAME: 'flask-special.com'
