version: '3.3'

services:
  studentportal:
    container_name: studentportal
    ports:
      - "8080:5000"
    networks:
      - studentportal:
          aliases:
              - flas-app
      - mongodb

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - studentportal
    volumes:
      - ./nginx.conf:./nginx.conf

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mongodb
    volumes:
      - "assets:/data/assets"
      - "mongodb-data:/data/db"
    environment:
      MONGO_INITDB_DATABASE="studentportal"
      MONGO_INITDB_ROOT_USERNAME=mongo_user
      MONGO_INITDB_ROOT_PASSWORD=mongo_secret

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    networks:
      - mongodb

networks:
    studentportal:
    mongodb:

volumes:
    assets:
    mongodb-data:
