version: '3.3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret
  mongo-express:
    container_name: mongo-express
    image: mongo-express

  studentportal:
    container_name: studentportal

networks:
    frontend:

volumes:
    mongo-data:
    assets: