version: '3.3'

services:
  studentportal:
    container_name: studentportal
    build: .
    depends_on:
      - mongodb
    networks:
      - frontend
      - database

  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on:
      - studentportal
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - database
    volumes:
      - "mongodb-data:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=studentportal
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_secret
    command: mongorestore ./mongo-seed/studentportal-dump

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - webserver
      - mongodb
    ports:
      - "8083:8081"
    networks:
      - frontend
      - database
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_secret


networks:
    frontend:
    database:

volumes:
    assets:
    mongodb-data:
