version: '3.3'

services:
  studentportal:
    container_name: studentportal
    depends_on:
      - webserver
      - mongodb
    build: .
    ports:
      - "8080:5000"
    networks:
      app:
        aliases:
         - flask-app
      mongodb:

  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
    volumes:
      - ./nginx.conf:./nginx.conf

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
      - "assets:/data/assets"
      - "mongodb-data:/data/db"
    environment:
      - MONGO_INITDB_DATABASE="studentportal"
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_secret
    command: /mongo-seed/import.sh

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - mongodb

networks:
    app:
    mongodb:

volumes:
    assets:
    mongodb-data:
