version: '3.3'

services:
  studentportal:
    container_name: studentportal
    depends_on:
      - webserver
      - database
    build: .
    ports:
      - "8080:5000"
    networks:
      app:
        aliases:
         - flask-app
      mongodb:

  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
    volumes:
      - ./nginx.conf:./nginx.conf

  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - database
    volumes:
      - "mongodb-data:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=studentportal
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_secret
    command: mongorestore ./mongo-seed/studentportal-dump

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8083:8081"
    networks:
      - database
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example


networks:
    app:
    database:

volumes:
    assets:
    mongodb-data:
