version: '3.3'

services:
  studentportal:
    container_name: studentportal
    build: .
    depends_on:
      - mongodb
    networks:
      - frontend
      - database
    environment:
      - SECRET_KEY=you-will-never-guess
      - MONGO_URI=mongodb://mongo_user:mongo_secret@mongodb:27017/studentportal

  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on:
      - studentportal
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./studentportal/static/:/static/

  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - database
    volumes:
      - mongodb-data:/data/db
      - ./mongo-seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    environment:
      - MONGO_INITDB_DATABASE=studentportal
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_secret

  mongo-seed:
    build: ./mongo-seed
    networks:
      - database

networks:
    frontend:
      driver: bridge
    database:
      driver: bridge

volumes:
    assets:
    mongodb-data:
